---

- name: Install bind9 and bind9-dnsutils 
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - bind9
    - bind9-dnsutils 

- name: Install named.conf.options
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  register: bind9options

- name: Install named.conf.local
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  register: bind9local

- name: Install zone key
  copy:
    content: "{{ dns_zone_key }}" 
    dest: /etc/bind/rndc.key
    mode: "0640" 
    owner: "bind"
    group: "bind"

- name: Ensure logging folder
  file:
    path: /var/log/named
    state: directory
    owner: "bind"
    group: "bind"

- name: enable bind9 service
  systemd:
    name: bind9.service
    enabled: yes
    state: started

- name: reload bind9
  raw: /usr/sbin/rndc reload
  when: bind9options.changed or bind9local.changed
