---

- name: Add backports repository
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    update_cache: yes
  when: 'ansible_distribution_release == "buster"'

- name: Install wireguard
  apt:
    name: wireguard
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: "root"
    group: "systemd-network" 

- name: Domain configs (supernode)
  include_tasks: per_domain.yml
  with_items: "{{domains}}"
  loop_control:
    loop_var: domain
  when: domains is defined

- name: Establish netlink worker
  include_tasks: netlink.yml
