---

- name: Ensure wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: "0650" 
    owner: "root"
    group: "systemd-network"    

- name: Place netlink config
  template:
    src: netlink_cfg.json.j2
    dest: /etc/wireguard/netlink_cfg.json

- name: Ensure wireguard srv directory
  file:
    path: /srv/wireguard
    state: directory

- name: Install setuptools and pyroute2
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - python3-setuptools
    - python3-pyroute2


- name: Fetch wireguard-vxlan-glue
  git:
    repo: 'https://github.com/freifunkh/wireguard-vxlan-glue.git'
    dest: /srv/wireguard/vxlan-glue
    version: deploy
  register: repo

- name: Install wg_netlink service
  template:
    src: netlink.service.j2
    dest: /etc/systemd/system/wg_netlink.service
  register: servicefile

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: servicefile.changed

- name: Enable netlink service
  systemd:
    name: wg_netlink.service
    state: restarted
    enabled: yes
  when: servicefile.changed or repo.changed
