---
servername: sn03
sn: 01

router_id: 5.145.135.153
public_ffrl_ipv4: "185.66.193.45/32"
public_ffrl_ipv6: "2a03:2260:3006:300::/56"
networkd_interfaces:
  - name: lo
    addresses:
      - "{{ public_ffrl_ipv4 }}"
      - "{{ public_ffrl_ipv6 }}"
    routing_policies:
      # rule for ipv4 ffrl
      - from: "{{ public_ffrl_ipv4 }}"
        table: 42
      # rule for ipv4 client network
      - from: "10.0.0.0/11"
        table: 42
      - from: "{{ public_ffrl_ipv6 }}"
        table: 42
  - name: eth0
    fixed_mac: bc:24:11:cb:d3 :58
    addresses:
      - 5.145.135.153/27
      - 2a00:fe0:43::203/64
    gateway4: 5.145.135.129
    gateway6: 2a00:fe0:43::1
    dns_server:
      - 9.9.9.9
      - "2a03:2260:3006::53"
    nat4: False
    nat6: False
    static_routes:
      - destination: "5.145.135.128/27"
        table: 42
      - destination: "2a00:fe0:43::/64"
        table: 42
    routing_policies:
      - from: "2a03:2260:3006:100::/56"
        table: 42
      - from: "2a03:2260:3006:200::/56"
        table: 42
      - from: "2a03:2260:3006:300::/56"
        table: 42
      - from: "185.66.193.45/32"
        table: 42
      - from: "10.0.0.0/11"
        table: 42
  - name: ens19
    addresses:
      - 100.64.17.153/24
# local_vxlan_supernode: 2a00:fe0:43::201
# remote_vxlan_supernode: 2a00:fe0:43::202
