---

- name: "Add ISC Kea repository key"
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/isc/kea-2-6/gpg.63D408891D8B8D01.key
    dest: /etc/apt/keyrings/isc-kea-cloudsmith.asc

- name: "Add ISC Kea repository"
  register: "iscrepositoryadded"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/isc-kea-cloudsmith.asc] https://dl.cloudsmith.io/public/isc/kea-2-6/deb/debian {{ ansible_distribution_release }} main"
    state: present

- name: "Update apt chache to get isc packages"
  apt:
    update_cache: "yes"
  when: "iscrepositoryadded is changed"

- name: "Install isc-kea-dhcp4-server"
  register: "keainstall"
  apt:
    name: "isc-kea-dhcp4-server"
  when: not ansible_check_mode

- name: "Remove SYSV init script"
  file:
    path: "/etc/init.d/isc-kea-dhcp4-server"
    state: "absent"

- name: "Add a ramdisk entry in fstab"
  notify: "Restart isc-kea-dhcp4-server"
  mount: 
    name: "/var/lib/kea"
    src: "tmpfs" 
    fstype: "tmpfs" 
    # with flaky clients which do not stop sending lease requests, 10M is not enough
    # resulting in DHCP service stopping
    opts: "defaults,size=64M" 
    state: "mounted"

- name: "Generate kea-dhcp4.conf config"
  notify: "Restart isc-kea-dhcp4-server"
  template:
    src: "kea-dhcp4.conf.j2"
    dest: "/etc/kea/kea-dhcp4.conf"
    mode: "0644"
    owner: "_kea"
    group: "_kea"

- name: "Create /etc/systemd/system/isc-kea-dhcp4-server.service.d directory if it does not exist"
  file:
    state: "directory"
    path: "/etc/systemd/system/isc-kea-dhcp4-server.service.d"
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Start isc-kea-dhcp4-server service"
  systemd:
    name: "isc-kea-dhcp4-server"
    state: "started"
    enabled: "yes"
    daemon_reload: "yes"