---

- name: Ensure wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: "root"
    group: "systemd-network" 

- name: Create the peers directory
  file:
    state: directory
    path: /etc/wireguard/peers-wg
    owner: auto

- name: Clone the peers git
  become: true
  become_user: auto
  git:
    repo: "{{ git_addr }}/peers-wg"
    dest: /etc/wireguard/peers-wg
    accept_hostkey: true
    version: main

- name: Install autoupdate peer script
  template:
    src: autoupdate_wg.py.j2
    dest: /home/auto/autoupdate_wg.py
    mode:  u=rwx,g=r,o=r
    owner: auto
    group: auto

- name: Set git config regarding pull strategy for auto user
  git_config:
    name: pull.ff
    value: only
    scope: system
    repo: /etc/wireguard/peers-wg

- name: Install cron
  apt:
    update_cache: yes
    name: "cron"

- name: Install crontab for autoupdate
  cron:
    name: "autoupdate wireguard peers from git"
    user: root
    minute: "*/1"
    job: >
      /home/auto/autoupdate_wg.py
